shellEmulator: true
trustPolicy: no-downgrade
minimumReleaseAge: 1440

packages:
  - apps/*
  - packages/*

catalog:
  typescript: ^5.9.3
  tsdown: ^0.16.8
  ws: ^8.18.3
  '@types/node': ^24.10.1
  '@types/ws': ^8.18.1

allowBuilds:
  esbuild: true
